version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - /c/Users/Deven/Desktop/Work/projects/who_wants_to_be_a_millionare/frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    restart: always

  backend:
    build: backend/
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    restart: always

  db:
    image: mongo
    container_name: mongo_db
    environment:
      - MONGO_INITDB_DATABASE=mongo_db
      - MONGO_INITDB_ROOT_USERNAME=deven
      - MONGO_INITDB_ROOT_PASSWORD=deven
    volumes:
      - mongo_db:/data/db
    restart: always

volumes:
  mongo_db:
    external: false
