db.questions.insertMany([
  {
    question: "How to a directory in Linux?",
    description: "delete folder",
    options: ["ls", "delete", "remove", "rmdir"],
    correct_answer: 3,
    explanation: "rmdir deletes an empty directory",
    difficulty: "Easy",
  },
  {
    question: "How to delete a directory in Windows?",
    description: "delete folder",
    options: ["ls", "del", "remove", "rmdir"],
    correct_answer: 2,
    explanation: "rmdir deletes an empty directory",
    difficulty: "Easy",
  },
  {
    question: "What is a Burgee?",
    description: "delete folder",
    options: ["Flag", "Rope", "Type of food", "Window"],
    correct_answer: 0,
    explanation: "rmdir deletes an empty directory",
    difficulty: "Easy",
  },
  {
    question: "Which sign of the zodiac comes between Virgo and Scorpio?",
    description: "delete folder",
    options: ["Libra", "Gemini", "Taurus", "Capricorn"],
    correct_answer: 0,
    explanation: "rmdir deletes an empty directory",
    difficulty: "Easy",
  },
  {
    question: "A statue of Charles Darwin sits in what London museum?",
    description: "delete folder",
    options: [
      "Tate",
      "British Museum",
      "Science Museum",
      "Natural History Museum",
    ],
    correct_answer: 3,
    explanation: "rmdir deletes an empty directory",
    difficulty: "Easy",
  },
  {
    question: "What was the first commerically available computer processor?",
    description: "delete folder",
    options: ["AMD AM386", "TMS 1000", "Intel 4004", "Intel 486SX"],
    correct_answer: 2,
    explanation: "rmdir deletes an empty directory",
    difficulty: "Easy",
  },
  {
    question: "In web design, what does CSS stand for?",
    description: "delete folder",
    options: [
      "Cascading Style Sheet",
      "Computer Style Sheet",
      "Counter Strike: Source",
      "Corrective Style Sheet",
    ],
    correct_answer: 0,
    explanation: "rmdir deletes an empty directory",
    difficulty: "Easy",
  },
]);
